### ISSUE TITLE
Skill/Proficiency System

### ISSUE THREAD

**Issue by Repentz** [AsYetUntitled/Framework#111]
Have a system implemented that gives the basics to rewards for repeating a process

- Fishing
- Mining
- Woodcutting
- Impounding
- Ticketing

Give perks for these per level, such as faster processing, use of better tools per level like drills for mining rather than pickaxes, chainsaws, etc.

Give more % of ticket to actual cop per ticket, jail, etc.

Just a suggestion, I've requested it be added to the framework before because I think it would add alot to the RP aspect of AL. You can also have skill system = True or False for people who don't want it.

**Comment by policeman18** [comment]
+1

**Comment by Latouth** [comment]
+1

**Comment by fresqo** [comment]
IMO, This should either be IN as a new standard feature or not put in. Please don't put as option as its too much code to just sit around if not used.

**Comment by tkcjesse** [comment]
Yeah. Exactly. I personally think it shouldn't be in. I know multiple people who hate it and also people who like it.

**Comment by MJRamon** [comment]
Players like progression. Players like to be awarded for repetative work. This is good and healthy approach and has to be built-in.

**Comment by BoGuu** [comment]
Despite the fact there is two pull requests for arguably 'non Framework' things, I do not stray away from the fact that this is still a Framework, and features such as this do not entirely belong on it.

There are lots of servers out there that have put countless hours of work into their code base, making things such as this. So for it to become a default in the Framework (for every server to have), would be disappointing. There is a reason why some servers are good, and some are bad, a lot of that boils down to the content, I don't feel it's right to let somebody take 5 minutes to achieve what took some months.

**Comment by tkcjesse** [comment]
Hah. You know i agree dawg.

**Comment by fresqo** [comment]
most mmorpg/rpg games have a leveling system of some sort (even just a general playing lvl) i think arma life mods kinda need it tbh.

**Comment by Emma-L** [comment]
I think what is trying to be said, although I may be in danger of repeating what others have said before me, is that if you had spent time and effort trying to make your server stand out, and had developed this amazing skills system, it would be awfully upsetting to see it become a standard. Some servers are fun to play on and attract players due to innovative development, but, at the latter end of the scale, servers with little development are typically boring and doomed to fail. If things like the skills system are put into the framework, this will allow undeserving servers to suddenly have something worthwhile, whilst simulaneously devaluing (so to speak) the system itself, as now everyone has it. Thus, those who have spent countless hours trying to make their systems have suddenly just wasted their time, which hardly seems fair, and no longer stand out in the sea of Life servers.

**Comment by tkcjesse** [comment]
Exactly what emma said. Servers today succeed due to skill of the developers. If we add all this shit that the popular servers hadn anyone can just match the system. This is why i stopped my original intent to do skill systems public. If we did this it'll be just like exile. 3,000 servers all the same. With only a 1,000 players. Exile server to player ratio is about 3:1. Thats awful. Personally this stuff being added imo would kill the AL community even further. Let the real server owners and dedicated developers shine. If you want the stuff and can't do it. Pay someone.

**Comment by SimZor** [comment]
I'm very much against this aswell. Should be kept as a framework only as @BoGuu said.
