### ISSUE TITLE
Battleye no RCON connection possible

### ISSUE THREAD

**Issue by yololetsplay** [AsYetUntitled/Framework#147]
<What should have happened?>
I setup manually beconfig.cfg in /arma3server/serverfiles/battleye with
```
RConIP MYIPINHERE
RConPort 2306
RConPassword myrconpw
```
because the file does not exists.
I tried startparams -bepath=./battleye - no connection.
What's wrong? On my server the firewall is inactive, so it cannot block.

I cannot connect using "Dart" or "EPM RCon" :/

Greetz,
yololetsplay

**Comment by setoy** [comment]
Not a repo issue.

**Comment by yololetsplay** [comment]
Are you sure? Maybe something is missed, e.g. some important files.

**Comment by setoy** [comment]
>Are you sure? 

Yes.

> Maybe something is missed, e.g. some important files.

No.

**Comment by Jawshy** [comment]
As @setoy said this issue is not related to the framework in any shape or form. BattlEye including its RCon protocol and Altis Life RPG are not related. 

Please see [support](https://www.battleye.com/support/) on the BattlEye website and [BattlEye](https://community.bistudio.com/wiki/BattlEye) on the Bohemia Interactive Community Wiki for more information regarding your issue. For support see [contact](https://github.com/AsYetUntitled/Framework/blob/master/.github/CONTRIBUTING.md#contact).

**Comment by SimZor** [comment]
Omfg lmao

**Comment by tkcjesse** [comment]
Wow.
