### ISSUE TITLE
weapon Attachments not found or not usable. with CBA enable

### ISSUE THREAD

**Issue by pabclsn** [AsYetUntitled/Framework#347]
Hi guys I made a post on the CBA team github, commy2 told me to ask you so here I am here is  a link of our conversation. 

https://github.com/CBATeam/CBA_A3/issues/721

Game version: 1.72

Altis Life 4.4r4 ,extDB2, infiSTAR, Task Force Radio.

Branch: master

**Comment by ColinM9991** [comment]
We don't actively support mods so I'd say this doesn't belong on GitHub issue tracking because this is a place for bugs that are introduced via development, or lack of.

Unless any other contributer/admin has an issue then I'll close this in an hour or 2.

Please post this on the Discord if you need help from another community member.

**Comment by pabclsn** [comment]
Ok thanks a lot @ColinM9991
