### ISSUE TITLE
Altis Life 5.0.0 vehicle unflip menu 

### ISSUE THREAD

**Issue by Jedediasz** [AsYetUntitled/Framework#384]
Hi

I added new vehicles to mission, and I have no option to unflip Prowler Qilin, Ambulance, MB 4WD, 4WD IDAP. How to fix it? 

https://www.altisliferpg.com/topic/3631-altis-life-500-vehicle-unflip-menu/

Altis Life 5.0.0
Launcher version: 1.5.142859
Game version: 1.76.142872

**Comment by Jawshy** [comment]
Hi, @Jedediasz. Thanks for your interest in the framework repository. [GitHub Issues](https://help.github.com/articles/about-issues/) are only for bugs, suggestions, or other tasks related **to the current build** of the mission on the [repository](https://github.com/AsYetUntitled/Framework/). As your issue is none of the former (because you said that you've edited the mission files), please seek help in the _appropriate channel_ on the [ArmA RPG Life](https://discord.gg/EaB7Jgw) Discord server, or you can wait for a reply to your forum post.

Furthermore, before you submit issue tickets, please read over the [contributing guidelines for this repository](https://github.com/AsYetUntitled/Framework/blob/master/.github/CONTRIBUTING.md) and, if reporting a bug, fill in the _entire_ [issue template](https://raw.githubusercontent.com/AsYetUntitled/Framework/master/.github/ISSUE_TEMPLATE.md). This helps @AsYetUntitled collaborators understand and reproduce the reported bug so it may be resolved sooner than later. Thanks.
