### ISSUE TITLE
Money Hack

### ISSUE THREAD

**Issue by SalihF7** [AsYetUntitled/Framework#418]
money making:

1- We are entering the game 
2- Disable the Battleye Service from the service manager
3- We'll use cheat engine, first select ArmA 3 and enter the money then we'll see 17 option.
4- If our money is 16.000.000 there will be 2 more 0. We'll select that. Click speed at the right bottom and set the money what we want. Then we'll close cheat engine and close the game from task manager.

### Expected behaviour
* Player kick and cash set 0 and bank 0 vs.

### Actual behaviour
Cash added and bank

Mission version: Version 5.0.0
Launcher version: 1.5.143751
Game version: 1.80.143869

**Comment by Heavybob** [comment]
When you say service manager, do you mean task manager? Doing that should autokick you if you're connected to a battleye enabled server.

**Comment by SalihF7** [comment]
Yes task manager and server battleye enable you try

**Comment by Heavybob** [comment]
I don't believe you. This sounds too autistic to work and if it does, well rip.

**Comment by LeventHAN** [comment]
It does @Heavybob 
I was the guy who found it.
İf you close battleye from task mng you had 15-20 sec to change the value and them get kicked. However it got patched... This was somewhere 1 month ago... SalihF7 you only need to open your battleye by changing 0 to 1... İ already said this to you months ago

**Comment by SalihF7** [comment]
@LeventHAN But İf using "ProccesKiller" Battleye kick time 1-2 minutes up.

**Comment by LeventHAN** [comment]
Make a video as proof mention your script base version and open new issue. Since this issue isn't general but specific to your server/script it is hard to believe without graphic proof. If you need support use also discord of altis life rpg. I did stop with Arma 3 so I can't help you eighter, just try to make a proof and show the other mods the issue @salihf7 Kolay gelsin! Baska birsey olursa bana ulasirsin zaten...
