### ISSUE TITLE
PlayerTags for whitelists player

### ISSUE THREAD

**Issue by BraK3NN** [AsYetUntitled/Framework#443]
### Expected behaviour
Name tag like this
http://prntscr.com/jcp2a6

### Actual behaviour
but right now
http://prntscr.com/jcp2on

Playertags.sqf
https://hastebin.com/ekuhiholek.cs

**Comment by imKLM** [comment]
I can see that you have modified the file, we intend for GitHub issues to be used to report any issues with the current code of the framework so that they can be fixed. This however sounds like an issue caused by files you have modified. For issues like this please use our Discord server: https://discord.gg/ajGUDSH

**Comment by Leigham** [comment]
there has been multiple commits like this now, that hasn't been an issue with the framework but the edits you make yourself. 
Issues, are for issues with the frameworks, not issues with the developer making changes.

**Comment by Wackbatt** [comment]
Issue unrelated to the framework.
