### ISSUE TITLE
storageBox glitch

### ISSUE THREAD

**Issue by akane777222** [AsYetUntitled/Framework#586]
### Expected behaviour

If you install the storageBox about 2/3 at home, it will pop out. Glitch that makes it easy to sling this with a helicopter

### Actual behaviour

If you install the storageBox about 2/3 at home, it will pop out. Glitch that makes it easy to sling this with a helicopter

### Steps to reproduce the behaviour
1. 
Just watch the video
https://youtu.be/jXYs72cOELA

Mission version: 5.0

**Comment by akane777222** [comment]
Can someone help me with the test? I couldn't do it right in the video, but it can bounce off the road. I can't do it because I'm new. I saw a lot of people doing

**Comment by klmunday** [comment]
After a discussion with Akane777222 it became clear that he claims people are abusing the disabled collision of the house storage boxes to fling them into the road, there they can be sling loaded via helicopters and allow the owner to have a larger virtual inventory space (+700) to use during jobs etc which yields a larger return for job runs.

I propose that we should keep the collision toggle of the boxes since this means players cannot kill other players whilst placing them and to instead add either a whitelist or blacklist to sling loadin. This could be achieved via the RopeAttach and RopeBreak event handlers
