### ISSUE TITLE
Sync Data Dupe Glitch

### ISSUE THREAD

**Issue by crimilo** [AsYetUntitled/Framework#639]
### Expected behaviour

You take the items, hit sync data, give them back to your friend/veichle, press ALT F4, join back to the server and you don't have those items.

### Actual behaviour

You take the items, hit sync data, give them back to your friend/veichle, press ALT F4, join back to the server. You have the items and your friend/veichle as well.

### Steps to reproduce the behaviour

Two ways:
1. Somone drop his loadout on the ground. You take it, hit sync data in Y menù, drop it back to your friend and wait until he took all the items, press ALT + F4 or force close in task manager, join back to the server, enjoy your duped loadout.
2. hit sync data in Y menù (with your loadout), put your loadout in your veichle inventory, press ALT F4, join back to th server, enojy duped loadout.

### [RPT](https://community.bistudio.com/wiki/Crash_Files#Arma_3) and/or extDB3 logs (if applicable)

----

Mission version: 
v5.0.0

Launcher version: 
 1.5.146096

Game version:
1.96.146114

Branch:
main / beta branch not specified

**Comment by TaktischerSpeck** [comment]
only thing you can do is to sync the gear of the player on DC.
That means you use the on DC EVH and you need to rewrite you save gear script a bit so that you can execute it with any unit not only on player.
than its fixed

**Comment by MartinezDeveloper** [comment]
life_server\Functions\Systems\fn_clientDisconnect.sqf

put **[] call SOCK_fnc_updateRequest;** above this **[_uid] spawn TON_fnc_houseCleanup;**

**Comment by Gonzka** [comment]
> life_server\Functions\Systems\fn_clientDisconnect.sqf
> 
> put **[] call SOCK_fnc_updateRequest;** above this **[_uid] spawn TON_fnc_houseCleanup;**

You mean **[] remoteExecCall ["SOCK_fnc_updateRequest",_unit];**. Otherwise it wont work server-side ^^

**Comment by AngryHerring** [comment]
Tested using **[] call SOCK_fnc_updateRequest** (yes, even with remoteExecCall, no target sadly).
Fix? Creating a similar script server-side.

Again, creating such a script, will implement even more exploits. One to mention is:
 - Disconnecting when inside 3D-Clothing shop, (something selected, but not purchased. Gear is previewed on your character), as these will be synced to the database.

Edit: Adds to the point its stupid to directly add items to the player, instead of adding it to a created "dummy unit". https://community.bistudio.com/wiki/createVehicleLocal (typeOf player createVehicleLocal)
